# Generated by Django 5.2.7 on 2025-10-21 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('vehicle_plate', models.CharField(max_length=16)),
                ('vehicle_make', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('theft_datetime', models.DateTimeField()),
                ('theft_place', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reports_videos/')),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('ANALYSIS', 'W trakcie analizy'), ('MATCHED', 'Dopasowano'), ('UNMATCHED', 'Brak dopasowania'), ('UNCERTAIN', 'Niepewne'), ('CLOSED', 'Zamknięte')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
