# Generated by Django 5.2.7 on 2025-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('NEW', 'Oczekujące'), ('ANALYSIS', 'W trakcie analizy'), ('MATCHED', 'Dopasowano'), ('UNCERTAIN', 'Niepewne'), ('UNMATCHED', 'Brak dopasowania'), ('CLOSED', 'Zamknięte')], default='NEW', max_length=16),
        ),
    ]
