# Generated by Django 5.2.7 on 2025-10-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='formal_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='owner_address_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='owner_address_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='owner_address_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='owner_first_name',
            field=models.CharField(default='Brak', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='owner_last_name',
            field=models.CharField(default='Brak', max_length=80),
        ),
        migrations.AddField(
            model_name='report',
            name='police_report_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='special_marks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='suspect_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='witness_info',
            field=models.TextField(blank=True),
        ),
    ]
