# Generated by Django 5.2.7 on 2025-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_additional_notes_report_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='owner_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner_last_name',
            field=models.CharField(max_length=80),
        ),
    ]
