# Generated by Django 5.2.7 on 2025-11-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_owner_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='vehicle_plate_detected',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
