# Generated by Django 5.2.7 on 2025-11-05 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_vehicle_plate_detected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='evidence/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='evidence/videos/')),
                ('detected_plates_json', models.TextField(blank=True, help_text='Lista wykrytych tablic (JSON).')),
                ('match_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'W kolejce'), ('MATCHED', 'Dopasowano'), ('UNCERTAIN', 'Niepewne'), ('UNMATCHED', 'Brak dopasowania')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to=settings.AUTH_USER_MODEL)),
                ('matched_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='reports.report')),
            ],
        ),
    ]
